// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    partial class RestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Property<Guid>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaEntregaId")
                        .HasColumnType("int");

                    b.Property<int>("PrecioTotal")
                        .HasColumnType("int");

                    b.HasKey("ComandaId");

                    b.HasIndex("FormaEntregaId");

                    b.ToTable("Comanda", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ComandaMercaderia", b =>
                {
                    b.Property<int>("MercaderiaId")
                        .HasColumnType("int");

                    b.Property<Guid>("ComandaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ComandaMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComandaMercaderiaId"));

                    b.HasKey("MercaderiaId", "ComandaId");

                    b.HasIndex("ComandaId");

                    b.ToTable("ComandaMercaderia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FormaEntrega", b =>
                {
                    b.Property<int>("FormaEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormaEntregaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FormaEntregaId");

                    b.ToTable("FormaEntrega", (string)null);

                    b.HasData(
                        new
                        {
                            FormaEntregaId = 1,
                            Descripcion = "Salon"
                        },
                        new
                        {
                            FormaEntregaId = 2,
                            Descripcion = "Delivery"
                        },
                        new
                        {
                            FormaEntregaId = 3,
                            Descripcion = "Pedidos Ya"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.Property<int>("MercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MercaderiaId"));

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<string>("Preparacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipoMercaderiaId")
                        .HasColumnType("int");

                    b.HasKey("MercaderiaId");

                    b.HasIndex("TipoMercaderiaId");

                    b.ToTable("Mercaderia", (string)null);

                    b.HasData(
                        new
                        {
                            MercaderiaId = 1,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "2 tazas de harina de trigo\r\n| 1 cucharadita de sal\r\n| 1/2 taza de agua tibia\r\n| 1/4 taza de aceite de oliva\r\n| 1 cebolla picada\r\n| 2 dientes de ajo picados\r\n| 1/2 kilo de carne molida\r\n| 1/2 cucharadita de comino",
                            Nombre = "Empanadas de Carne",
                            Precio = 300,
                            Preparacion = "En un bol grande, mezcla la harina y la sal. Agrega el agua tibia y el aceite de oliva. Amasa hasta que quede una masa suave y homogénea.\r\n| Cubre la masa con un paño y déjala reposar durante 30 minutos.\r\n| Precalienta el horno a 200°C.",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 2,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "8 láminas de papel de arroz\r\n| 150 gramos de fideos de arroz\r\n| 1 zanahoria rallada\r\n| 1/2 pepino rallado\r\n| 1/4 taza de cilantro fresco picado\r\n| 8 hojas de lechuga\r\n| 8 hojas de menta fresca\r\n| 1 cucharada de salsa de soja",
                            Nombre = "Rollitos de primavera",
                            Precio = 1186,
                            Preparacion = "Coloca los fideos de arroz en un recipiente y cúbrelos con agua caliente. Déjalos reposar durante 10-15 minutos o hasta que estén blandos. Escúrrelos y reserva",
                            TipoMercaderiaId = 1
                        },
                        new
                        {
                            MercaderiaId = 3,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "4 pechugas de pollo sin piel, cortadas en cubos\r\n| 1 cebolla picada\r\n| 3 dientes de ajo picados\r\n| 2 cucharadas de jengibre fresco rallado\r\n| 2 cucharadas de curry en polvo\r\n| 1 lata de leche de coco\r\n| 1/2 taza de caldo de pollo",
                            Nombre = "Pollo al Curry",
                            Precio = 1500,
                            Preparacion = "En una olla o sartén grande, calienta el aceite de oliva a fuego medio. Agrega la cebolla y cocina hasta que esté suave y translúcida, unos 5 minutos.\r\n| Agrega el ajo, el jengibre y el curry en polvo y cocina por un minuto, hasta que estén fragantes",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 4,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "4 filetes de carne (puedes usar carne de res, pollo o ternera)\r\n| 2 huevos batidos\r\n| 1 taza de pan rallado\r\n| Sal y pimienta al gusto\r\n| Aceite vegetal para freír\r\n| 4 rebanadas de jamón\r\n| 4 rebanadas de queso mozzarella",
                            Nombre = "Milanesa Napolitana",
                            Precio = 1800,
                            Preparacion = "Prepara los filetes de carne: aplana cada uno con un mazo de carne o con un rodillo, hasta que tengan un grosor de aproximadamente 1 cm. Sazónalos con sal y pimienta al gusto",
                            TipoMercaderiaId = 2
                        },
                        new
                        {
                            MercaderiaId = 5,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "12-15 placas de canelones\r\n| 1 calabacín mediano\r\n| 1 berenjena mediana\r\n| 2 zanahorias medianas\r\n| 1 cebolla mediana\r\n| 2 dientes de ajo picados\r\n| 1 taza de espinacas frescas\r\n| 2 tazas de salsa de tomate",
                            Nombre = "Canelones de Verdura",
                            Precio = 1600,
                            Preparacion = "Precalienta el horno a 180°C.\r\n| Cocina las placas de canelones según las instrucciones del paquete, hasta que estén al dente. Escúrrelas y enjuágalas con agua fría para detener la cocción. Reserva",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 6,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "1 paquete de sorrentinos de jamón y queso (puedes encontrarlos en la sección de congelados)\r\n| 2 cucharadas de aceite de oliva\r\n| 1 cebolla picada finamente\r\n| 2 dientes de ajo picados finamente\r\n| 1/2 taza de caldo de pollo",
                            Nombre = "Sorrentinos de Jamon y Queso",
                            Precio = 1650,
                            Preparacion = "Cocina los sorrentinos en agua hirviendo con sal durante el tiempo recomendado en el paquete, hasta que estén al dente. Escúrrelos y resérvalos.\r\n| Calienta el aceite de oliva en una sartén a fuego medio",
                            TipoMercaderiaId = 3
                        },
                        new
                        {
                            MercaderiaId = 7,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "4 bifes de chorizo de 250 gramos cada uno\r\n| Sal gruesa\r\n| Pimienta negra molida\r\n| Aceite de oliva",
                            Nombre = "Bife de chorizo",
                            Precio = 2100,
                            Preparacion = "Retira los bifes de chorizo de la nevera y deja que se pongan a temperatura ambiente durante 30 minutos antes de cocinarlos.\r\n| Precalienta la parrilla a fuego alto y cepilla la parrilla con aceite de oliva para evitar que la carne se pegue",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 8,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "1 kilo de carne de asado (puede ser bife de chorizo, vacío, entraña, costillar, o el corte de tu preferencia)\r\n| Sal gruesa\r\n| Chimichurri (opcional)",
                            Nombre = "Asado",
                            Precio = 2500,
                            Preparacion = "Retira la carne de la nevera y deja que se ponga a temperatura ambiente durante 30-45 minutos antes de cocinarla.\r\n| Prepara la parrilla y asegúrate de que las brasas estén calientes.\r\n| Espolvorea la carne con sal gruesa",
                            TipoMercaderiaId = 4
                        },
                        new
                        {
                            MercaderiaId = 9,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "Masa de pizza (puedes hacerla casera o comprarla lista)\r\n| 1 taza de salsa de tomate\r\n| 250 gramos de mozzarella fresca\r\n| 10 hojas de albahaca fresca\r\n| Aceite de oliva",
                            Nombre = "Pizza Margarita",
                            Precio = 1950,
                            Preparacion = "Precalienta el horno a 220 grados Celsius.\r\n| Extiende la masa de pizza sobre una bandeja para horno. Si la masa es casera, asegúrate de hornearla ligeramente antes de agregar los ingredientes, esto ayudará a que quede crujiente",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 10,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "Masa de pizza (puedes hacerla casera o comprarla lista)\r\n| 1 taza de salsa de tomate\r\n| 150 gramos de queso mozzarella rallado\r\n| 50 gramos de queso gorgonzola o queso azul\r\n| 50 gramos de queso de cabra\r\n| 50 gramos de queso parmesano rallado",
                            Nombre = "Pizza Cuatro Quesos",
                            Precio = 2200,
                            Preparacion = "Precalienta el horno a 220 grados Celsius.\r\n| Extiende la masa de pizza sobre una bandeja para horno. Si la masa es casera, asegúrate de hornearla ligeramente antes de agregar los ingredientes, esto ayudará a que quede crujiente.",
                            TipoMercaderiaId = 5
                        },
                        new
                        {
                            MercaderiaId = 11,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "2 latas de atún en agua, escurrido\r\n| 1/4 de taza de mayonesa\r\n| 1/4 de taza de cebolla picada finamente\r\n| 2 cucharadas de jugo de limón\r\n| 1 cucharadita de mostaza dijon\r\n| 1/4 de cucharadita de sal\r\n| 1/4 de cucharadita de pimienta",
                            Nombre = "Sandwich de atún",
                            Precio = 1000,
                            Preparacion = "En un tazón grande, mezcla el atún, la mayonesa, la cebolla, el jugo de limón, la mostaza, la sal y la pimienta.\r\n| Corta los panes por la mitad y coloca una hoja de lechuga y una rodaja de tomate en cada pan",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 12,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "4 panes para panini\r\n| 8 rebanadas de jamón cocido\r\n| 8 rebanadas de queso mozzarella\r\n| 1/4 de taza de pesto de albahaca\r\n| 2 cucharadas de mantequilla derretida",
                            Nombre = "Panini de jamón y queso",
                            Precio = 800,
                            Preparacion = "Precalienta una sandwichera o plancha a fuego medio-alto.\r\n| Abre los panes para panini y unta el pesto de albahaca en la mitad inferior de cada pan.\r\n| Coloca 2 rebanadas de jamón cocido y 2 rebanadas de queso mozzarella sobre el pesto",
                            TipoMercaderiaId = 6
                        },
                        new
                        {
                            MercaderiaId = 13,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "1 lechuga romana grande, lavada y cortada en trozos\r\n| 2 tazas de crutones\r\n| 1/2 taza de queso parmesano rallado\r\n| 2 pechugas de pollo, cocidas y cortadas en tiras\r\n| Sal y pimienta al gusto\r\n| Aceite de oliva\r\n| Aderezo César",
                            Nombre = "Ensalada César",
                            Precio = 1050,
                            Preparacion = "En una sartén grande, calienta un poco de aceite de oliva a fuego medio. Agrega las tiras de pollo y sazona con sal y pimienta al gusto",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaId = 14,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "1 lechuga romana, lavada y cortada en trozos\r\n| 1 taza de tomates cherry, cortados por la mitad\r\n| 1/2 taza de aceitunas negras, sin hueso\r\n| 1/2 taza de pepinos, cortados en rodajas\r\n| 1/2 taza de queso feta, desmenuzado",
                            Nombre = "Ensalada Mediterránea",
                            Precio = 1150,
                            Preparacion = "En un tazón grande, mezcla la lechuga romana, los tomates cherry, las aceitunas negras, los pepinos, el queso feta y la cebolla roja",
                            TipoMercaderiaId = 7
                        },
                        new
                        {
                            MercaderiaId = 15,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "1 litro de agua\r\n4 limones grandes\r\n| 1/2 taza de azúcar (o al gusto)\r\n| Hielo al gusto",
                            Nombre = "Agua fresca",
                            Precio = 500,
                            Preparacion = "Exprime los limones para obtener el jugo y reserva.\r\nEn una jarra grande, mezcla el agua y el azúcar hasta que el azúcar se disuelva por completo.\r\n| Agrega el jugo de limón a la jarra y mezcla bien",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 16,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "4-6 naranjas maduras\r\n| Azúcar o edulcorante al gusto (opcional)\r\n| Agua fría (opcional)",
                            Nombre = "Jugo de Naranja",
                            Precio = 600,
                            Preparacion = "Lava bien las naranjas y córtalas por la mitad.\r\n| Usa un exprimidor de cítricos para exprimir las naranjas y obtener el jugo. Si no tienes un exprimidor, puedes cortar las naranjas en trozos y procesarlas en una licuadora hasta obtener un líquido",
                            TipoMercaderiaId = 8
                        },
                        new
                        {
                            MercaderiaId = 17,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "4 kg de malta de cebada (pale ale)\r\n| 350 g de malta crystal 40L\r\n| 350 g de malta Vienna\r\n| 20 g de lúpulo Warrior (60 minutos)\r\n| 30 g de lúpulo Citra (20 minutos)\r\n| 30 g de lúpulo Galaxy (20 minutos)",
                            Nombre = "Galaxitra - American IPA",
                            Precio = 1550,
                            Preparacion = "Macera las maltas en agua a 66°C durante 60 minutos.\r\n| Filtra el mosto y ponlo a hervir.\r\n| Añade 20 g de lúpulo Warrior al inicio de la cocción y deja hervir durante 60 minutos.\r\n| A los 20 minutos, añade 30 g de lúpulo Citra",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 18,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "4 kg de malta Pilsner\r\n| 1 kg de malta Vienna\r\n| 500 g de malta Munich\r\n| 500 g de malta Crystal 40L\r\n| 200 g de malta Wheat\r\n| 500 g de azúcar belga (candi sugar)\r\n| 30 g de lúpulo Saaz (60 minutos)",
                            Nombre = "Flanders Red - Sour Power",
                            Precio = 1550,
                            Preparacion = "Macera las maltas en agua a 66°C durante 60 minutos.\r\n| Filtra el mosto y ponlo a hervir.\r\n| Añade el azúcar belga y el lúpulo Saaz al inicio de la cocción y deja hervir durante 60 minutos",
                            TipoMercaderiaId = 9
                        },
                        new
                        {
                            MercaderiaId = 19,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "500 gramos de queso mascarpone\r\n3 huevos\r\n| 150 gramos de azúcar\r\n| 300 ml de café fuerte\r\n| 200 gramos de bizcochos de soletilla\r\n| Cacao en polvo",
                            Nombre = "Tiramisú",
                            Precio = 700,
                            Preparacion = "Separa las claras y las yemas de los huevos en dos tazones diferentes.\r\n| Añade el azúcar a las yemas y bátelas hasta que se vuelvan pálidas y espumosas.\r\n| Añade el queso mascarpone a la mezcla de yemas y azúcar y mezcla bien.",
                            TipoMercaderiaId = 10
                        },
                        new
                        {
                            MercaderiaId = 20,
                            Imagen = "Imagen.PNG",
                            Ingredientes = "1 lata de leche condensada (397 gramos)\r\n| 2 tazas de leche entera\r\n| 4 huevos\r\n| 1 cucharadita de esencia de vainilla\r\n| 1/2 taza de azúcar",
                            Nombre = "Flan",
                            Precio = 600,
                            Preparacion = "Precalienta el horno a 180°C.\r\n| En una olla, calienta la leche condensada y la leche entera a fuego medio, removiendo constantemente, hasta que estén bien mezcladas",
                            TipoMercaderiaId = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.TipoMercaderia", b =>
                {
                    b.Property<int>("TipoMercaderiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMercaderiaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoMercaderiaId");

                    b.ToTable("TipoMercaderia", (string)null);

                    b.HasData(
                        new
                        {
                            TipoMercaderiaId = 1,
                            Descripcion = "Entrada"
                        },
                        new
                        {
                            TipoMercaderiaId = 2,
                            Descripcion = "Minutas"
                        },
                        new
                        {
                            TipoMercaderiaId = 3,
                            Descripcion = "Pastas"
                        },
                        new
                        {
                            TipoMercaderiaId = 4,
                            Descripcion = "Parrilla"
                        },
                        new
                        {
                            TipoMercaderiaId = 5,
                            Descripcion = "Pizzas"
                        },
                        new
                        {
                            TipoMercaderiaId = 6,
                            Descripcion = "Sandwich"
                        },
                        new
                        {
                            TipoMercaderiaId = 7,
                            Descripcion = "Ensaladas"
                        },
                        new
                        {
                            TipoMercaderiaId = 8,
                            Descripcion = "Bebidas"
                        },
                        new
                        {
                            TipoMercaderiaId = 9,
                            Descripcion = "Cerveza Artesanal"
                        },
                        new
                        {
                            TipoMercaderiaId = 10,
                            Descripcion = "Postres"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.HasOne("Domain.Entities.FormaEntrega", "FormaEntrega")
                        .WithMany("Comandas")
                        .HasForeignKey("FormaEntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaEntrega");
                });

            modelBuilder.Entity("Domain.Entities.ComandaMercaderia", b =>
                {
                    b.HasOne("Domain.Entities.Comanda", "Comanda")
                        .WithMany("ComandasMercaderias")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Mercaderia", "Mercaderia")
                        .WithMany("ComandasMercaderias")
                        .HasForeignKey("MercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Mercaderia");
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.HasOne("Domain.Entities.TipoMercaderia", "TipoMercaderia")
                        .WithMany("Mercaderias")
                        .HasForeignKey("TipoMercaderiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoMercaderia");
                });

            modelBuilder.Entity("Domain.Entities.Comanda", b =>
                {
                    b.Navigation("ComandasMercaderias");
                });

            modelBuilder.Entity("Domain.Entities.FormaEntrega", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("Domain.Entities.Mercaderia", b =>
                {
                    b.Navigation("ComandasMercaderias");
                });

            modelBuilder.Entity("Domain.Entities.TipoMercaderia", b =>
                {
                    b.Navigation("Mercaderias");
                });
#pragma warning restore 612, 618
        }
    }
}
